### ISSUE TITLE
the link to download 'VTC_v1.0_public.csv.tar.gz' is invalid

### ISSUE THREAD

**Issue by peiliu0408** [unitaryai/VTC-dataset#1]
I am seeking to download VTC-dataset as mentioned in README, but the download link "https://github.com/unitaryai/VTC/releases/download/v0.1.0-alpha/VTC_v1.0_public.csv.tar.gz" seems invalid anymore.

is there a new link to download annotations file?

thanks

**Comment by jamt9000** [comment]
Hello! Look like the repo name was wrong in that link. You can see the right link here: https://github.com/unitaryai/VTC-dataset/releases

https://github.com/unitaryai/VTC-dataset/releases/download/v0.1.0-alpha/VTC_v1.0_public.csv.tar.gz

I've now updated the README, thanks for pointing out the mistake!
